import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Link from "next/link";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Botpress v3.3 script */}
        <Script
          src="https://cdn.botpress.cloud/webchat/v3.3/inject.js"
          strategy="afterInteractive"
        />

        {/* Inject chat container styling */}
        <style>{`
          #webchat .bpWebchat {
            position: unset;
            width: 100%;
            height: 100%;
            max-height: 100%;
            max-width: 100%;
          }

          #webchat .bpFab {
            display: none;
          }
        `}</style>
      </head>
      <body className="bg-zinc-950 text-zinc-100">
        {/* === Global Navigation === */}
        <nav className="fixed top-0 left-0 right-0 z-50 bg-zinc-950/80 backdrop-blur-md border-b border-zinc-800">
          <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
            <Link href="/" className="text-lg font-bold text-amber-500 hover:text-amber-400">
              Henry Tavarez
            </Link>
            <div className="flex gap-6 text-sm">
              <Link href="/projects" className="hover:text-amber-400 transition">
                Projects
              </Link>
              <Link href="/about" className="hover:text-amber-400 transition">
                About
              </Link>
              <Link href="/resume" className="hover:text-amber-400 transition">
                Résumé
              </Link>
              <Link href="/contact" className="hover:text-amber-400 transition">
                Contact
              </Link>
            </div>
          </div>
        </nav>

        {/* Main content wrapper */}
        <main className="min-h-[calc(100vh-4rem)] pt-16 bg-zinc-950">
          {children}
        </main>

        {/* Chat container required for Botpress v3.3 */}
        {/* Chat container as fixed */}
        <div
          id="webchat"
          className="fixed bottom-6 right-6 w-[420px] h-[560px] hidden"
        ></div>
        {/* Initialize Botpress after the script loads */}
        <Script id="botpress-init" strategy="afterInteractive">
          {`
            function initializeBotpress() {
              if (window.botpress && typeof window.botpress.init === "function") {
                // ❌ Removed auto-open so chat stays hidden until toggled
                window.botpress.init({
                  botId: "0d1251e2-411d-4cbd-a0f8-3302266afb9f",
                  configuration: {
                    version: "v2",
                    composerPlaceholder: "",
                    botName: "Henry’s UX Portfolio Assistant",
                    botDescription: "Discover Henry’s UX journey — ask me about his design philosophy or key projects.",
                    website: {},
                    email: {},
                    phone: {},
                    termsOfService: {},
                    privacyPolicy: {},
                    color: "#E91E63",
                    variant: "solid",
                    headerVariant: "glass",
                    themeMode: "light",
                    fontFamily: "inter",
                    radius: 4,
                    feedbackEnabled: false,
                    footer: "[⚡ by Botpress](https://botpress.com/?from=webchat)",
                    soundEnabled: false,
                    proactiveMessageEnabled: false,
                    proactiveBubbleMessage: "Hi! 👋 Need help?",
                    proactiveBubbleTriggerType: "afterDelay",
                    proactiveBubbleDelayTime: 10
                  },
                  clientId: "4c7013bc-fc0a-4e19-ad82-c9a54129c8b6",
                  selector: "#webchat"
                });
              } else {
                // Retry after a short delay if the script hasn't loaded yet
                setTimeout(initializeBotpress, 500);
              }
            }
            initializeBotpress();
          `}
        </Script>
        
      </body>
    </html>
  );
}
